# Generated by Django 4.2.11 on 2026-09-14 10:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Funsonariu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "nre",
                    models.CharField(max_length=20, unique=True, verbose_name="NRE"),
                ),
                (
                    "naran",
                    models.CharField(max_length=100, verbose_name="Naran Kompletu"),
                ),
                (
                    "kargu",
                    models.CharField(blank=True, max_length=100, verbose_name="Kargu"),
                ),
                (
                    "unidade_traballu",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=100,
                        verbose_name="Departamentu",
                    ),
                ),
                (
                    "grau",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("I", "Grau I"),
                            ("II", "Grau II"),
                            ("III", "Grau III"),
                            ("IV", "Grau IV"),
                        ],
                        max_length=5,
                        verbose_name="Grau",
                    ),
                ),
                (
                    "numeru_telefoni",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Númeru Telefoni"
                    ),
                ),
                (
                    "foto",
                    models.ImageField(blank=True, null=True, upload_to="foto_pegawai/"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_admin", models.BooleanField(default=False)),
                ("data_tama", models.DateField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Funsonáriu",
                "verbose_name_plural": "Funsonáriu Sira",
                "db_table": "api_funsonariu",
                "ordering": ["naran"],
            },
        ),
        migrations.CreateModel(
            name="KonfigurasaunSistema",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "oras_tama_hahu",
                    models.TimeField(
                        default="06:00:00", verbose_name="Orijem Tama Dadersan"
                    ),
                ),
                (
                    "oras_tama_remata",
                    models.TimeField(
                        default="08:00:00", verbose_name="Limite Tama Dadersan"
                    ),
                ),
                (
                    "oras_sai_deskansa",
                    models.TimeField(
                        default="12:00:00", verbose_name="Orijem Deskansa"
                    ),
                ),
                (
                    "oras_tama_lokraik",
                    models.TimeField(
                        default="13:30:00", verbose_name="Orijem Tama Lokraik"
                    ),
                ),
                (
                    "oras_sai_lokraik",
                    models.TimeField(
                        default="17:30:00", verbose_name="Orijem Sai / Fila"
                    ),
                ),
                (
                    "limite_raio_metru",
                    models.IntegerField(default=50, verbose_name="Raio GPS (Metru)"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "last_message",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Mensajen ikus ba App"
                    ),
                ),
            ],
            options={
                "verbose_name": "Konfigurasaun Sistema",
                "verbose_name_plural": "Konfigurasaun Sistema",
                "db_table": "api_konfigurasaun_sistema",
            },
        ),
        migrations.CreateModel(
            name="LoronFeriadu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data_feriadu",
                    models.DateField(unique=True, verbose_name="Data Libur"),
                ),
                (
                    "katerangan",
                    models.CharField(max_length=200, verbose_name="Katerangan Libur"),
                ),
            ],
            options={
                "verbose_name": "Loron Feriadu",
                "verbose_name_plural": "Loron Feriadu",
                "db_table": "api_loron_feriadu",
                "ordering": ["-data_feriadu"],
            },
        ),
        migrations.CreateModel(
            name="ViolaLokalizasaun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tempu",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Tempu Detekta"
                    ),
                ),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("distansia_metru", models.FloatField(verbose_name="Distánsia (m)")),
                (
                    "last_status",
                    models.CharField(max_length=50, verbose_name="Estadu Absensi"),
                ),
                (
                    "funsonariu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="violasaun_gps",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Funsonáriu",
                    ),
                ),
            ],
            options={
                "verbose_name": "Violação Geofence",
                "verbose_name_plural": "Violação Geofence sira",
                "db_table": "api_violasaun_gps",
                "ordering": ["-tempu"],
            },
        ),
        migrations.CreateModel(
            name="Presensa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tempu_tama",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Tama Dadersan"
                    ),
                ),
                (
                    "tempu_sai_deskansa",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deskansa"
                    ),
                ),
                (
                    "tempu_tama_lokraik",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Tama Lokraik"
                    ),
                ),
                (
                    "tempu_sai",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Sai / Fila Lokraik"
                    ),
                ),
                ("latitude", models.FloatField(verbose_name="Latitude GPS")),
                ("longitude", models.FloatField(verbose_name="Longitude GPS")),
                (
                    "distansia_metru",
                    models.FloatField(verbose_name="Distánsia ba Kantór (metru)"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("prezente", "Prezente"),
                            ("tardiu", "Tardiu"),
                            ("prezente_balun", "Prezente Balun"),
                            ("falta", "Falta / La Iha"),
                            ("horas_ekstra", "Horas Ekstra"),
                            ("lisensa", "Lisensa / Izin"),
                            ("moras", "Moras"),
                            ("ferias", "Férias"),
                        ],
                        db_index=True,
                        default="prezente",
                        max_length=20,
                        verbose_name="Estadu",
                    ),
                ),
                ("komentariu", models.TextField(blank=True, verbose_name="Komentáriu")),
                (
                    "durasaun_horas_ekstra",
                    models.FloatField(
                        default=0.0, verbose_name="Durasaun Horas Ekstra (Jam)"
                    ),
                ),
                (
                    "funsonariu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="presensa",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Funsonáriu",
                    ),
                ),
            ],
            options={
                "verbose_name": "Presensa",
                "verbose_name_plural": "Rekapitulasaun Presensa",
                "db_table": "api_presensa",
                "ordering": ["-tempu_tama"],
            },
        ),
        migrations.CreateModel(
            name="PediduLisensa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipu_lisensa",
                    models.CharField(
                        choices=[
                            ("moras", "Moras (Sakit)"),
                            ("lisensa", "Lisensa (Izin)"),
                            ("ferias", "Férias (Cuti)"),
                            ("urjente", "Mendesak (Emergency)"),
                        ],
                        max_length=10,
                        verbose_name="Tipe Izin",
                    ),
                ),
                ("data_hahu", models.DateField(verbose_name="Data Hahu")),
                ("data_remata", models.DateField(verbose_name="Data Remata")),
                ("razaun", models.TextField(verbose_name="Razaun / Komentáriu")),
                (
                    "file_evidensia",
                    models.ImageField(
                        upload_to="bukti_izin/", verbose_name="Foto Evidénsia / Surat"
                    ),
                ),
                (
                    "estadu_pedidu",
                    models.CharField(
                        choices=[
                            ("hein", "Hein (Pending)"),
                            ("aprova", "Aprova (Approved)"),
                            ("rejeita", "Rejeita (Rejected)"),
                        ],
                        default="hein",
                        max_length=20,
                        verbose_name="Estadu Pedidu",
                    ),
                ),
                ("tempu_pedidu", models.DateTimeField(auto_now_add=True)),
                (
                    "funsonariu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pedidu_lisensa",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Funsonáriu",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pedidu Lisensa",
                "verbose_name_plural": "Pedidu Lisensa sira",
                "db_table": "api_pedidu_lisensa",
                "ordering": ["-tempu_pedidu"],
            },
        ),
    ]
