# Generated by Django 4.2.11 on 2026-04-04 20:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Pegawai",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "nik",
                    models.CharField(max_length=20, unique=True, verbose_name="NIK"),
                ),
                ("nama", models.CharField(max_length=100, verbose_name="Nama Lengkap")),
                (
                    "jabatan",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Jabatan"
                    ),
                ),
                (
                    "unit_kerja",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Unit Kerja"
                    ),
                ),
                (
                    "golongan",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("I", "Golongan I"),
                            ("II", "Golongan II"),
                            ("III", "Golongan III"),
                            ("IV", "Golongan IV"),
                        ],
                        max_length=5,
                        verbose_name="Golongan",
                    ),
                ),
                (
                    "no_hp",
                    models.CharField(blank=True, max_length=20, verbose_name="No. HP"),
                ),
                (
                    "foto",
                    models.ImageField(blank=True, null=True, upload_to="foto_pegawai/"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_admin", models.BooleanField(default=False)),
                ("tanggal_bergabung", models.DateField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Pegawai",
                "verbose_name_plural": "Data Pegawai",
                "ordering": ["nama"],
            },
        ),
        migrations.CreateModel(
            name="Absensi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "waktu_masuk",
                    models.DateTimeField(auto_now_add=True, verbose_name="Waktu Masuk"),
                ),
                ("latitude", models.FloatField(verbose_name="Latitude GPS")),
                ("longitude", models.FloatField(verbose_name="Longitude GPS")),
                (
                    "jarak_meter",
                    models.FloatField(verbose_name="Jarak ke Kantor (meter)"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("hadir", "Hadir"),
                            ("terlambat", "Terlambat"),
                            ("lembur", "Lembur"),
                        ],
                        default="hadir",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                ("keterangan", models.TextField(blank=True, verbose_name="Keterangan")),
                (
                    "pegawai",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="absensi",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Pegawai",
                    ),
                ),
            ],
            options={
                "verbose_name": "Absensi",
                "verbose_name_plural": "Rekap Absensi",
                "ordering": ["-waktu_masuk"],
            },
        ),
    ]
