# Generated by Django 4.2.11 on 2026-04-04 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="absensi",
            name="status",
            field=models.CharField(
                choices=[
                    ("hadir", "Hadir"),
                    ("terlambat", "Terlambat"),
                    ("lembur", "Lembur"),
                ],
                db_index=True,
                default="hadir",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="absensi",
            name="waktu_masuk",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, verbose_name="Waktu Masuk"
            ),
        ),
        migrations.AlterField(
            model_name="pegawai",
            name="unit_kerja",
            field=models.CharField(
                blank=True, db_index=True, max_length=100, verbose_name="Unit Kerja"
            ),
        ),
    ]
