# Generated by Django 4.2.11 on 2026-09-15 12:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShiftServisu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("naran", models.CharField(max_length=100, verbose_name="Naran Shift")),
                (
                    "oras_tama_hahu",
                    models.TimeField(
                        default="06:00:00", verbose_name="Orijem Tama Dadersan"
                    ),
                ),
                (
                    "oras_tama_remata",
                    models.TimeField(
                        default="08:00:00", verbose_name="Limite Tama Dadersan"
                    ),
                ),
                (
                    "oras_sai_deskansa",
                    models.TimeField(
                        default="12:00:00", verbose_name="Orijem Deskansa"
                    ),
                ),
                (
                    "oras_tama_lokraik",
                    models.TimeField(
                        default="13:30:00", verbose_name="Orijem Tama Lokraik"
                    ),
                ),
                (
                    "oras_sai_lokraik",
                    models.TimeField(
                        default="17:30:00", verbose_name="Orijem Sai / Fila"
                    ),
                ),
            ],
            options={
                "verbose_name": "Shift Servisu",
                "verbose_name_plural": "Shift Servisu sira",
                "db_table": "api_shift_servisu",
            },
        ),
        migrations.AddField(
            model_name="funsonariu",
            name="device_id",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Device ID (HP)"
            ),
        ),
        migrations.AddField(
            model_name="funsonariu",
            name="kuota_cuti_anual",
            field=models.IntegerField(default=12, verbose_name="Kuota Cuti (Loron)"),
        ),
        migrations.AddField(
            model_name="funsonariu",
            name="manajer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="subordinados",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Manajer/Atasan",
            ),
        ),
        migrations.AddField(
            model_name="pedidulisensa",
            name="estadu_manajer",
            field=models.CharField(
                choices=[
                    ("hein", "Hein (Pending)"),
                    ("aprova", "Aprova (Approved)"),
                    ("rejeita", "Rejeita (Rejected)"),
                ],
                default="hein",
                max_length=20,
                verbose_name="Aprovamentu Manajer",
            ),
        ),
        migrations.AlterField(
            model_name="pedidulisensa",
            name="estadu_pedidu",
            field=models.CharField(
                choices=[
                    ("hein", "Hein (Pending)"),
                    ("aprova", "Aprova (Approved)"),
                    ("rejeita", "Rejeita (Rejected)"),
                ],
                default="hein",
                max_length=20,
                verbose_name="Aprovamentu Final (HR)",
            ),
        ),
        migrations.CreateModel(
            name="PediduLembur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_lembur", models.DateField(verbose_name="Data Lembur")),
                ("oras_hahu", models.TimeField(verbose_name="Oras Hahu")),
                ("oras_remata", models.TimeField(verbose_name="Oras Remata")),
                ("razaun", models.TextField(verbose_name="Razaun / Tarefa")),
                (
                    "estadu_manajer",
                    models.CharField(
                        choices=[
                            ("hein", "Hein (Pending)"),
                            ("aprova", "Aprova (Approved)"),
                            ("rejeita", "Rejeita (Rejected)"),
                        ],
                        default="hein",
                        max_length=20,
                        verbose_name="Aprovamentu Manajer",
                    ),
                ),
                (
                    "estadu_hr",
                    models.CharField(
                        choices=[
                            ("hein", "Hein (Pending)"),
                            ("aprova", "Aprova (Approved)"),
                            ("rejeita", "Rejeita (Rejected)"),
                        ],
                        default="hein",
                        max_length=20,
                        verbose_name="Aprovamentu Final (HR)",
                    ),
                ),
                ("tempu_pedidu", models.DateTimeField(auto_now_add=True)),
                (
                    "funsonariu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pedidu_lembur",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Funsonáriu",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pedidu Lembur",
                "verbose_name_plural": "Pedidu Lembur sira",
                "db_table": "api_pedidu_lembur",
                "ordering": ["-data_lembur", "-tempu_pedidu"],
            },
        ),
        migrations.AddField(
            model_name="funsonariu",
            name="shift",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.shiftservisu",
                verbose_name="Shift Servisu",
            ),
        ),
    ]
