# Generated by Django 4.2.11 on 2026-04-04 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_absensi_status_alter_absensi_waktu_masuk_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="absensi",
            name="waktu_keluar",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Waktu Keluar"
            ),
        ),
    ]
