# Generated by Django 4.2.11 on 2026-04-05 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_absensi_waktu_keluar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="absensi",
            name="status",
            field=models.CharField(
                choices=[
                    ("hadir", "Hadir"),
                    ("terlambat", "Terlambat"),
                    ("hadir_sebagian", "Hadir Sebagian"),
                    ("alpha", "Alpha / Tidak Hadir"),
                    ("lembur", "Lembur"),
                ],
                db_index=True,
                default="hadir",
                max_length=20,
                verbose_name="Status",
            ),
        ),
    ]
