# Generated by Django 4.2.11 on 2026-04-05 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_absensi_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="absensi",
            name="waktu_keluar_istirahat",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Waktu Keluar Istirahat"
            ),
        ),
        migrations.AddField(
            model_name="absensi",
            name="waktu_masuk_siang",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Waktu Masuk Siang"
            ),
        ),
        migrations.AlterField(
            model_name="absensi",
            name="waktu_keluar",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Waktu Keluar Sore"
            ),
        ),
        migrations.AlterField(
            model_name="absensi",
            name="waktu_masuk",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, verbose_name="Waktu Masuk Pagi"
            ),
        ),
    ]
