# Generated by Django 4.2.11 on 2026-04-07 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_absensi_waktu_keluar_istirahat_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name='pegawai',
            old_name='nik',
            new_name='nre',
        ),
        migrations.RenameField(
            model_name='pegawai',
            old_name='nama',
            new_name='naran',
        ),
        migrations.RenameField(
            model_name='pegawai',
            old_name='jabatan',
            new_name='kargu',
        ),
        migrations.RenameField(
            model_name='pegawai',
            old_name='unit_kerja',
            new_name='unidade_traballu',
        ),
        migrations.RenameField(
            model_name='pegawai',
            old_name='golongan',
            new_name='grau',
        ),
        migrations.RenameField(
            model_name='pegawai',
            old_name='no_hp',
            new_name='numeru_telefoni',
        ),
        migrations.RenameField(
            model_name='pegawai',
            old_name='tanggal_bergabung',
            new_name='data_tama',
        ),
        migrations.RenameField(
            model_name='absensi',
            old_name='waktu_masuk',
            new_name='tempu_tama',
        ),
        migrations.RenameField(
            model_name='absensi',
            old_name='waktu_keluar_istirahat',
            new_name='tempu_sai_deskansa',
        ),
        migrations.RenameField(
            model_name='absensi',
            old_name='waktu_masuk_siang',
            new_name='tempu_tama_lokraik',
        ),
        migrations.RenameField(
            model_name='absensi',
            old_name='waktu_keluar',
            new_name='tempu_sai',
        ),
        migrations.RenameField(
            model_name='absensi',
            old_name='jarak_meter',
            new_name='distansia_metru',
        ),
        migrations.RenameField(
            model_name='absensi',
            old_name='keterangan',
            new_name='komentariu',
        ),
    ]
