# Generated by Django 4.2.11 on 2026-04-07 18:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_rename_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="PengaturanSistem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "jam_masuk_mulai",
                    models.TimeField(
                        default="06:00:00", verbose_name="Orijem Tama Dadersan"
                    ),
                ),
                (
                    "jam_masuk_akhir",
                    models.TimeField(
                        default="08:00:00", verbose_name="Limite Tama Dadersan"
                    ),
                ),
                (
                    "jam_keluar_istirahat",
                    models.TimeField(
                        default="12:00:00", verbose_name="Orijem Deskansa"
                    ),
                ),
                (
                    "jam_masuk_siang",
                    models.TimeField(
                        default="13:30:00", verbose_name="Orijem Tama Lokraik"
                    ),
                ),
                (
                    "jam_keluar_sore",
                    models.TimeField(
                        default="17:30:00", verbose_name="Orijem Sai / Fila"
                    ),
                ),
                (
                    "batas_radius_meter",
                    models.IntegerField(default=50, verbose_name="Raio GPS (Metru)"),
                ),
            ],
            options={
                "verbose_name": "Konfigurasaun Sistema",
                "verbose_name_plural": "Konfigurasaun Sistema",
            },
        ),
        migrations.AlterModelOptions(
            name="absensi",
            options={
                "ordering": ["-tempu_tama"],
                "verbose_name": "Presensa",
                "verbose_name_plural": "Rekapitulasaun Presensa",
            },
        ),
        migrations.AlterModelOptions(
            name="pegawai",
            options={
                "ordering": ["naran"],
                "verbose_name": "Funsonáriu",
                "verbose_name_plural": "Dadus Funsonáriu",
            },
        ),
        migrations.AddField(
            model_name="absensi",
            name="durasi_lembur",
            field=models.FloatField(
                default=0.0, verbose_name="Durasaun Horas Ekstra (Jam)"
            ),
        ),
        migrations.AlterField(
            model_name="absensi",
            name="distansia_metru",
            field=models.FloatField(verbose_name="Distánsia ba Kantór (metru)"),
        ),
        migrations.AlterField(
            model_name="absensi",
            name="komentariu",
            field=models.TextField(blank=True, verbose_name="Komentáriu"),
        ),
        migrations.AlterField(
            model_name="absensi",
            name="pegawai",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="absensi",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Funsonáriu",
            ),
        ),
        migrations.AlterField(
            model_name="absensi",
            name="status",
            field=models.CharField(
                choices=[
                    ("hadir", "Prezente"),
                    ("terlambat", "Tardiu"),
                    ("hadir_sebagian", "Prezente Balun"),
                    ("alpha", "Falta / La Iha"),
                    ("lembur", "Horas Ekstra"),
                    ("izin", "Lisensa / Izin"),
                    ("sakit", "Moras"),
                    ("cuti", "Férias"),
                ],
                db_index=True,
                default="hadir",
                max_length=20,
                verbose_name="Estadu",
            ),
        ),
        migrations.AlterField(
            model_name="absensi",
            name="tempu_sai",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Sai / Fila Lokraik"
            ),
        ),
        migrations.AlterField(
            model_name="absensi",
            name="tempu_sai_deskansa",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Deskansa"),
        ),
        migrations.AlterField(
            model_name="absensi",
            name="tempu_tama",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, verbose_name="Tama Dadersan"
            ),
        ),
        migrations.AlterField(
            model_name="absensi",
            name="tempu_tama_lokraik",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Tama Lokraik"
            ),
        ),
        migrations.AlterField(
            model_name="pegawai",
            name="grau",
            field=models.CharField(
                blank=True,
                choices=[
                    ("I", "Grau I"),
                    ("II", "Grau II"),
                    ("III", "Grau III"),
                    ("IV", "Grau IV"),
                ],
                max_length=5,
                verbose_name="Grau",
            ),
        ),
        migrations.AlterField(
            model_name="pegawai",
            name="kargu",
            field=models.CharField(blank=True, max_length=100, verbose_name="Kargu"),
        ),
        migrations.AlterField(
            model_name="pegawai",
            name="naran",
            field=models.CharField(max_length=100, verbose_name="Naran Kompletu"),
        ),
        migrations.AlterField(
            model_name="pegawai",
            name="nre",
            field=models.CharField(max_length=20, unique=True, verbose_name="NRE"),
        ),
        migrations.AlterField(
            model_name="pegawai",
            name="numeru_telefoni",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="Númeru Telefoni"
            ),
        ),
        migrations.AlterField(
            model_name="pegawai",
            name="unidade_traballu",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=100,
                verbose_name="Unidade Traballu",
            ),
        ),
        migrations.CreateModel(
            name="PengajuanIzin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipe_izin",
                    models.CharField(
                        choices=[
                            ("sakit", "Moras (Sakit)"),
                            ("izin", "Lisensa (Izin)"),
                            ("cuti", "Férias (Cuti)"),
                        ],
                        max_length=10,
                        verbose_name="Tipe Izin",
                    ),
                ),
                ("tanggal_mulai", models.DateField(verbose_name="Data Hahu")),
                ("tanggal_selesai", models.DateField(verbose_name="Data Remata")),
                ("keterangan", models.TextField(verbose_name="Razaun / Komentáriu")),
                (
                    "file_bukti",
                    models.ImageField(
                        upload_to="bukti_izin/", verbose_name="Foto Evidénsia / Surat"
                    ),
                ),
                (
                    "status_pengajuan",
                    models.CharField(
                        choices=[
                            ("menunggu", "Hein (Pending)"),
                            ("disetujui", "Aprova (Approved)"),
                            ("ditolak", "Rejeita (Rejected)"),
                        ],
                        default="menunggu",
                        max_length=20,
                        verbose_name="Estadu Pedidu",
                    ),
                ),
                ("waktu_pengajuan", models.DateTimeField(auto_now_add=True)),
                (
                    "pegawai",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pengajuan_izin",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Funsonáriu",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pedidu Lisensa",
                "verbose_name_plural": "Pedidu Lisensa sira",
                "ordering": ["-waktu_pengajuan"],
            },
        ),
    ]
