# Generated by Django 4.2.11 on 2026-04-07 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_pengaturansistem_alter_absensi_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="HariLibur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tanggal", models.DateField(unique=True, verbose_name="Data Libur")),
                (
                    "keterangan",
                    models.CharField(max_length=200, verbose_name="Katerangan Libur"),
                ),
            ],
            options={
                "verbose_name": "Hari Libur",
                "verbose_name_plural": "Hari Libur",
                "ordering": ["-tanggal"],
            },
        ),
        migrations.AddField(
            model_name="pengaturansistem",
            name="tarif_lembur_per_jam",
            field=models.IntegerField(default=0, verbose_name="Tarif Lembur per Jam"),
        ),
        migrations.AlterField(
            model_name="pengajuanizin",
            name="tipe_izin",
            field=models.CharField(
                choices=[
                    ("sakit", "Moras (Sakit)"),
                    ("izin", "Lisensa (Izin)"),
                    ("cuti", "Férias (Cuti)"),
                    ("mendesak", "Mendesak (Emergency)"),
                ],
                max_length=10,
                verbose_name="Tipe Izin",
            ),
        ),
    ]
