# Generated by Django 4.2.11 on 2026-04-07 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_harilibur_pengaturansistem_tarif_lembur_per_jam_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pengaturansistem",
            name="last_message",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Mensajen ikus ba App"
            ),
        ),
        migrations.AddField(
            model_name="pengaturansistem",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
