# Generated by Django 4.2.11 on 2026-04-07 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_pengaturansistem_last_message_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="harilibur",
            options={
                "ordering": ["-tanggal"],
                "verbose_name": "Loron Feriadu",
                "verbose_name_plural": "Loron Feriadu",
            },
        ),
        migrations.AlterModelOptions(
            name="pegawai",
            options={
                "ordering": ["naran"],
                "verbose_name": "Funsonáriu",
                "verbose_name_plural": "Funsonáriu Sira",
            },
        ),
        migrations.AlterField(
            model_name="pegawai",
            name="unidade_traballu",
            field=models.CharField(
                blank=True, db_index=True, max_length=100, verbose_name="Departamentu"
            ),
        ),
        migrations.AlterModelTable(
            name="absensi",
            table="api_presensa",
        ),
        migrations.AlterModelTable(
            name="harilibur",
            table="api_loron_feriadu",
        ),
        migrations.AlterModelTable(
            name="pegawai",
            table="api_funsonariu",
        ),
        migrations.AlterModelTable(
            name="pengajuanizin",
            table="api_pedidu_lisensa",
        ),
        migrations.AlterModelTable(
            name="pengaturansistem",
            table="api_konfigurasaun_sistema",
        ),
    ]
