# Generated by Django 4.2.11 on 2026-04-07 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_alter_harilibur_options_alter_pegawai_options_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Pegawai",
            new_name="Funsonariu",
        ),
        migrations.RenameModel(
            old_name="Absensi",
            new_name="Presensa",
        ),
        migrations.RenameModel(
            old_name="PengajuanIzin",
            new_name="PediduLisensa",
        ),
        migrations.RenameModel(
            old_name="PengaturanSistem",
            new_name="KonfigurasaunSistema",
        ),
        migrations.RenameModel(
            old_name="HariLibur",
            new_name="LoronFeriadu",
        ),
        migrations.RenameField(
            model_name="presensa",
            old_name="pegawai",
            new_name="funsonariu",
        ),
        migrations.RenameField(
            model_name="pedidulisensa",
            old_name="pegawai",
            new_name="funsonariu",
        ),
    ]
