# Generated by Django 4.2.11 on 2026-04-07 21:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_pedidulisensa_presensa_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pedidulisensa",
            name="funsonariu",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pedidu_lisensa",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Funsonáriu",
            ),
        ),
        migrations.AlterField(
            model_name="presensa",
            name="funsonariu",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="presensa",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Funsonáriu",
            ),
        ),
    ]
