# Generated by Django 4.2.11 on 2026-04-07 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_alter_pedidulisensa_funsonariu_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="konfigurasaunsistema",
            name="tarif_lembur_per_jam",
        ),
    ]
