# Generated by Django 4.2.11 on 2026-04-07 21:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0013_remove_konfigurasaunsistema_tarif_lembur_per_jam"),
    ]

    operations = [
        migrations.CreateModel(
            name="ViolaLokalizasaun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tempu",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Tempu Detekta"
                    ),
                ),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("distansia_metru", models.FloatField(verbose_name="Distánsia (m)")),
                (
                    "last_status",
                    models.CharField(max_length=50, verbose_name="Estadu Absensi"),
                ),
                (
                    "funsonariu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="violasaun_gps",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Funsonáriu",
                    ),
                ),
            ],
            options={
                "verbose_name": "Violação Geofence",
                "verbose_name_plural": "Violação Geofence sira",
                "db_table": "api_violasaun_gps",
                "ordering": ["-tempu"],
            },
        ),
    ]
